// app/layout.js

export const dynamic = "force-dynamic";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/header/headerServer";
import { ClerkProvider } from '@clerk/nextjs';
import { Toaster } from "sonner";
import { ReduxProvider } from '@/app/lib/ReduxProvider.js';
import Footer from '@/components/footer.js';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CashClarity",
  description: "Generated by create RaunaK Kumar",
  icons: {
    icon: "/applogo.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className}`}>
          <ReduxProvider>
            <Header />
            <main className="min-h-screen">{children}</main>
            <Toaster richColors />
            <Footer />
          </ReduxProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
